# Generated by Django 4.0.4 on 2022-05-14 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('limit', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('is_online', models.BooleanField(default=False)),
                ('login_devices_count', models.IntegerField(default=0)),
                ('time', models.TimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_set', to='share_account_status_bot.user')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share_account_status_bot.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share_account_status_bot.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(through='share_account_status_bot.UserService', to='share_account_status_bot.service'),
        ),
    ]
