# Generated by Django 4.0.4 on 2022-05-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share_account_status_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('login_devices_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AccountStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('time', models.TimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share_account_status_bot.account')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share_account_status_bot.account')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(through='share_account_status_bot.ServiceAccount', to='share_account_status_bot.service'),
        ),
        migrations.DeleteModel(
            name='UserService',
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share_account_status_bot.service'),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share_account_status_bot.user'),
        ),
        migrations.AddField(
            model_name='accountstatus',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share_account_status_bot.service'),
        ),
        migrations.AddField(
            model_name='accountstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share_account_status_bot.user'),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_set', to='share_account_status_bot.user'),
        ),
        migrations.AddField(
            model_name='account',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share_account_status_bot.service'),
        ),
        migrations.AddField(
            model_name='account',
            name='users',
            field=models.ManyToManyField(through='share_account_status_bot.AccountStatus', to='share_account_status_bot.user'),
        ),
    ]
