# Generated by Django 4.0.4 on 2022-05-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_account_status_bot', '0002_account_accountstatus_serviceaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(through='share_account_status_bot.AccountStatus', to='share_account_status_bot.service'),
        ),
        migrations.DeleteModel(
            name='ServiceAccount',
        ),
    ]
